import type { Property } from '@/types/property'

export const MOCK_PROPERTIES: Property[] = [
  {
    id: '1',
    title: 'Departamento moderno en Polanco',
    type: 'apartment',
    listingType: 'sale',
    price: 4_200_000,
    pricePerSqm: 52000,
    area: 80,
    bedrooms: 2,
    bathrooms: 2,
    address: 'Presidente Masaryk 123',
    neighborhood: 'Polanco',
    city: 'CDMX',
    lat: 19.4340,
    lng: -99.1900,
    images: [],
    description: 'Departamento con acabados de lujo, cocina integral y estacionamiento.',
    broker: { id: 'b1', name: 'Carlos Herrera', avatar: 'CH', verified: true },
    createdAt: '2026-05-01',
    trend: 2.8,
  },
  {
    id: '2',
    title: 'Casa en Santa Fe con jardín',
    type: 'house',
    listingType: 'sale',
    price: 7_500_000,
    pricePerSqm: 36000,
    area: 208,
    bedrooms: 4,
    bathrooms: 3,
    address: 'Av. Santa Fe 456',
    neighborhood: 'Santa Fe',
    city: 'CDMX',
    lat: 19.3618,
    lng: -99.2600,
    images: [],
    description: 'Casa de lujo con jardín, alberca y cuarto de servicio.',
    broker: { id: 'b2', name: 'Andrea Martínez', avatar: 'AM', verified: true },
    createdAt: '2026-04-28',
    trend: 6.1,
  },
  {
    id: '3',
    title: 'Terreno en Xochimilco',
    type: 'land',
    listingType: 'sale',
    price: 1_800_000,
    pricePerSqm: 4500,
    area: 400,
    address: 'Calle 5 de Mayo 78',
    neighborhood: 'Xochimilco',
    city: 'CDMX',
    lat: 19.2650,
    lng: -99.1050,
    images: [],
    description: 'Terreno plano con uso de suelo habitacional H4.',
    createdAt: '2026-04-20',
    trend: 1.2,
  },
  {
    id: '4',
    title: 'Oficina en Reforma',
    type: 'office',
    listingType: 'rent',
    price: 35_000,
    pricePerSqm: 350,
    area: 100,
    address: 'Paseo de la Reforma 900',
    neighborhood: 'Reforma',
    city: 'CDMX',
    lat: 19.4270,
    lng: -99.1760,
    images: [],
    description: 'Oficina en piso 12 con vista a Reforma, estacionamiento incluido.',
    broker: { id: 'b1', name: 'Carlos Herrera', avatar: 'CH', verified: true },
    createdAt: '2026-05-05',
    trend: 0.4,
  },
  {
    id: '5',
    title: 'Departamento en Condesa',
    type: 'apartment',
    listingType: 'rent',
    price: 18_000,
    pricePerSqm: 300,
    area: 60,
    bedrooms: 1,
    bathrooms: 1,
    address: 'Sonora 230',
    neighborhood: 'Condesa',
    city: 'CDMX',
    lat: 19.4110,
    lng: -99.1720,
    images: [],
    description: 'Estudio luminoso cerca del Parque España.',
    createdAt: '2026-05-08',
    trend: 3.5,
  },
]
