import type { Listing } from '@/types/listing'

export const MOCK_LISTINGS: Listing[] = [
  // ── Physical ─────────────────────────────────────────────
  {
    id: 'p1',
    category: 'physical',
    physicalType: 'apartment',
    mode: 'sale',
    status: 'active',
    title: 'Departamento moderno en Polanco',
    description: 'Departamento con acabados de lujo, cocina integral, estacionamiento y roof garden.',
    price: 4_200_000,
    pricePerSqm: 52500,
    physical: {
      area: 80,
      bedrooms: 2,
      bathrooms: 2,
      parking: 1,
      address: 'Presidente Masaryk 123',
      neighborhood: 'Polanco',
      city: 'CDMX',
      state: 'CDMX',
      lat: 19.434,
      lng: -99.190,
    },
    images: [],
    tags: ['lujo', 'polanco', 'nuevaconstrucción'],
    seller: { id: 's1', name: 'Carlos Herrera', avatar: 'CH', verified: true, isBroker: true },
    viewCount: 342,
    favoriteCount: 28,
    createdAt: '2026-05-01',
    expiresAt: '2026-07-30',
    trend: 2.8,
    featured: true,
  },
  {
    id: 'p2',
    category: 'physical',
    physicalType: 'house',
    mode: 'sale',
    status: 'active',
    title: 'Casa con jardín y alberca en Santa Fe',
    description: 'Casa de lujo de 4 recámaras, jardín amplio, alberca, cuarto de servicio y 3 cajones.',
    price: 7_500_000,
    pricePerSqm: 36057,
    physical: {
      area: 208,
      bedrooms: 4,
      bathrooms: 3,
      parking: 3,
      address: 'Av. Santa Fe 456',
      neighborhood: 'Santa Fe',
      city: 'CDMX',
      state: 'CDMX',
      lat: 19.3618,
      lng: -99.260,
    },
    images: [],
    tags: ['santa fe', 'casa', 'alberca'],
    seller: { id: 's2', name: 'Andrea Martínez', avatar: 'AM', verified: true, isBroker: true },
    viewCount: 519,
    favoriteCount: 41,
    createdAt: '2026-04-28',
    expiresAt: '2026-07-27',
    trend: 6.1,
  },
  {
    id: 'p3',
    category: 'physical',
    physicalType: 'land',
    mode: 'sale',
    status: 'active',
    title: 'Terreno 400 m² uso H4 en Xochimilco',
    description: 'Terreno plano con uso de suelo habitacional H4, sin construcción, escrituras al día.',
    price: 1_800_000,
    pricePerSqm: 4500,
    physical: {
      area: 400,
      address: 'Calle 5 de Mayo 78',
      neighborhood: 'Xochimilco',
      city: 'CDMX',
      state: 'CDMX',
      lat: 19.265,
      lng: -99.105,
    },
    images: [],
    tags: ['terreno', 'xochimilco', 'inversión'],
    seller: { id: 's3', name: 'Roberto Jiménez', avatar: 'RJ', verified: false, isBroker: false },
    viewCount: 187,
    favoriteCount: 14,
    createdAt: '2026-04-20',
    expiresAt: '2026-07-19',
    trend: 1.2,
  },
  {
    id: 'p4',
    category: 'physical',
    physicalType: 'office',
    mode: 'rent',
    status: 'active',
    title: 'Oficina corporativa piso 12 en Reforma',
    description: 'Oficina de 100 m², piso 12, vista a Reforma, estacionamiento y sala de juntas.',
    price: 35_000,
    pricePerSqm: 350,
    physical: {
      area: 100,
      parking: 2,
      address: 'Paseo de la Reforma 900',
      neighborhood: 'Reforma',
      city: 'CDMX',
      state: 'CDMX',
      lat: 19.427,
      lng: -99.176,
    },
    images: [],
    tags: ['oficina', 'reforma', 'amoblado'],
    seller: { id: 's1', name: 'Carlos Herrera', avatar: 'CH', verified: true, isBroker: true },
    viewCount: 231,
    favoriteCount: 19,
    createdAt: '2026-05-05',
    expiresAt: '2026-08-03',
    trend: 0.4,
  },
  {
    id: 'p5',
    category: 'physical',
    physicalType: 'commercial',
    mode: 'sale',
    status: 'active',
    title: 'Local comercial en Av. Insurgentes',
    description: 'Local de 65 m², planta baja, alta afluencia, ideal para restaurante o retail.',
    price: 2_800_000,
    pricePerSqm: 43076,
    physical: {
      area: 65,
      address: 'Av. Insurgentes Sur 1200',
      neighborhood: 'Del Valle',
      city: 'CDMX',
      state: 'CDMX',
      lat: 19.385,
      lng: -99.170,
    },
    images: [],
    tags: ['local', 'insurgentes', 'comercial'],
    seller: { id: 's2', name: 'Andrea Martínez', avatar: 'AM', verified: true, isBroker: true },
    viewCount: 298,
    favoriteCount: 22,
    createdAt: '2026-05-03',
    expiresAt: '2026-08-01',
    trend: 3.1,
  },

  // ── Online / Digital ─────────────────────────────────────
  {
    id: 'o1',
    category: 'online',
    onlineType: 'saas',
    mode: 'sale',
    status: 'active',
    title: 'SaaS de facturación para PYMEs — $8k MRR',
    description: 'Plataforma de facturación CFDI para pequeñas empresas. 340 clientes activos, churn bajo, stack Node + React.',
    price: 960_000,
    multiplier: 10,
    online: {
      monthlyRevenue: 96_000,
      monthlyProfit: 61_000,
      monthlyTraffic: 4200,
      ageMonths: 38,
      techStack: ['Node.js', 'React', 'PostgreSQL', 'AWS'],
      monetization: ['Suscripción mensual'],
      employees: 2,
      reasonForSelling: 'Fundador se enfoca en otro proyecto.',
    },
    images: [],
    tags: ['saas', 'facturación', 'mrr', 'recurrente'],
    seller: { id: 's4', name: 'Diego Soria', avatar: 'DS', verified: true, isBroker: false },
    viewCount: 612,
    favoriteCount: 54,
    createdAt: '2026-05-07',
    expiresAt: '2026-08-05',
    featured: true,
  },
  {
    id: 'o2',
    category: 'online',
    onlineType: 'ecommerce',
    mode: 'sale',
    status: 'active',
    title: 'Tienda de suplementos deportivos — $45k/mes ventas',
    description: 'E-commerce de suplementos con marca propia, inventario incluido, Shopify, logística tercerizada.',
    price: 540_000,
    multiplier: 4,
    online: {
      monthlyRevenue: 135_000,
      monthlyProfit: 27_000,
      monthlyTraffic: 18000,
      ageMonths: 24,
      techStack: ['Shopify', 'Meta Ads', 'Google Ads'],
      monetization: ['Ventas directas'],
      employees: 1,
      reasonForSelling: 'Reubicación internacional.',
    },
    images: [],
    tags: ['ecommerce', 'shopify', 'suplementos', 'marca'],
    seller: { id: 's5', name: 'Valeria Cruz', avatar: 'VC', verified: true, isBroker: false },
    viewCount: 489,
    favoriteCount: 37,
    createdAt: '2026-05-06',
    expiresAt: '2026-08-04',
  },
  {
    id: 'o3',
    category: 'online',
    onlineType: 'content_site',
    mode: 'sale',
    status: 'active',
    title: 'Blog de finanzas personales — 80k visitas/mes',
    description: 'Sitio de contenido SEO sobre finanzas personales en español, monetizado con AdSense y afiliados.',
    price: 180_000,
    multiplier: 30,
    online: {
      monthlyRevenue: 6_000,
      monthlyProfit: 5_200,
      monthlyTraffic: 80_000,
      ageMonths: 48,
      techStack: ['WordPress', 'AdSense', 'Amazon Afiliados'],
      monetization: ['Display ads', 'Afiliados'],
      employees: 0,
      reasonForSelling: 'Consolidación de portafolio.',
    },
    images: [],
    tags: ['blog', 'seo', 'finanzas', 'pasivo'],
    seller: { id: 's6', name: 'Marco Reyes', avatar: 'MR', verified: false, isBroker: false },
    viewCount: 271,
    favoriteCount: 29,
    createdAt: '2026-05-02',
    expiresAt: '2026-07-31',
  },
  {
    id: 'o4',
    category: 'online',
    onlineType: 'newsletter',
    mode: 'sale',
    status: 'active',
    title: 'Newsletter de tecnología — 22k suscriptores',
    description: 'Newsletter semanal de tech en español, 42% tasa de apertura, monetizado con sponsors y afiliados.',
    price: 290_000,
    multiplier: 24,
    online: {
      monthlyRevenue: 12_000,
      monthlyProfit: 10_500,
      monthlyTraffic: 22_000,
      ageMonths: 30,
      techStack: ['Beehiiv', 'Substack export'],
      monetization: ['Sponsors', 'Afiliados'],
      employees: 1,
      reasonForSelling: 'Burnout creativo.',
    },
    images: [],
    tags: ['newsletter', 'tech', 'sponsor', 'audiencia'],
    seller: { id: 's4', name: 'Diego Soria', avatar: 'DS', verified: true, isBroker: false },
    viewCount: 344,
    favoriteCount: 31,
    createdAt: '2026-05-04',
    expiresAt: '2026-08-02',
  },
]
